name: Feature Request
description: Suggest an idea for HacKit
title: '[Feature Request] '
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Before opening a feauture request, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a feature request. To address this feature request as fast as possible, we need some information.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem or missing capability
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: If you have a solution in mind, please describe it.
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: Have you considered any alternative solutions or workarounds?